### ISSUE TITLE
Django admin panel

### ISSUE THREAD

**Issue by joaquinpco** [joaquinpco/DjBlog-CMS#1]
Adding Category Description throws an exception when using quotes "" or special characters
like  ά λ φ α.

**Comment by AceGentile** [comment]
Looks like this issue comes from utf8 encoding used in your mysql db. Seems there's not a "comfy" solution to that: basically you can move your db to an utf8mb4 encoding or change database type (say postgresql). 
Tried locally to apply utf8mb4 encoding and it worked.

**Comment by joaquinpco** [comment]
it works.
Close thread
